### ISSUE TITLE
Unable to translate larger XML documents

### ISSUE THREAD

**Issue by guppie70** [willemvlh/saxon-server#17]
When I try to POST a large(r) XML file to the /transform route, the app reports an error similar to below:
```
org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is java.lang.IllegalStateException: 
The multi-part request contained parameter data (excluding uploaded files) that exceeded the limit for maxPostSize set on the associated connectorxslt3service_1                |
 	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.handleParseFailure(StandardMultipartHttpServletRequest.java:124)xslt3service_1                |
 	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:115)xslt3service_1                |
 	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:88)xslt3service_1 
```
I have tried the following:
* Changed `application.properties` to this:
```
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-post-size=52428800
server.tomcat.max-form-request-size=52428800
```
* Added environment variables to the docker image in `docker-compose.yml` like this:
```
    environment:
      - SERVER_TOMCAT_MAX_POST_SIZE=52428800
      - SERVER_TOMCAT_MAX_FORM_REQUEST_SIZE=52428800
```
But to no avail.
I am not an experienced Java developer - does anyone know where I can configure this so that the error does not occur anymore?

**Comment by guppie70** [comment]
I ended up adding this file src/main/java/io/github/willemvlh/transformer/app/CustomWebServerFactory.java to the code base with this content:

```
package io.github.willemvlh.transformer.app;

import org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory;
import org.springframework.boot.web.server.WebServerFactoryCustomizer;
import org.springframework.boot.web.servlet.server.ConfigurableServletWebServerFactory;
import org.springframework.stereotype.Component;

@Component
public class CustomWebServerFactory
  implements WebServerFactoryCustomizer<ConfigurableServletWebServerFactory> {

  @Override
  public void customize(ConfigurableServletWebServerFactory factory) {
      // Increase the Tomcat max post size
      ((TomcatServletWebServerFactory) factory).addConnectorCustomizers(
          connector -> {
            connector.setMaxPostSize(10485760); // 10MB
          }
        );
    }
  }
}
```
In order to make that work, I added the below to pom.xml:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <version>3.0.2</version>
        </dependency>
```
I also upgraded org.springframework.boot to version `2.7.5`, but I have no clue if this helped with it finally working with large XML transformations.

**Comment by willemvlh** [comment]
Hi @guppie70,

It seems like these environment variables should do the trick:
  spring.servlet.multipart.max-file-size=xxx
  spring.servlet.multipart.max-request-size=xxx

I added them like this, there are probably easier ways to do this:

`docker run -p 5000:5000 -e "JAVA_OPTS=-Xmx1g" -e SPRING_APPLICATION_JSON='{"spring": {"servlet": {"multipart": {"max-file-size": "500MB", "max-request-size": "500MB"}}}}' --name saxon-server ghcr.io/willemvlh/saxon-server:v2.6`

I'll look into making this more user-friendly.
